// apps/error-tracking-upload-source-maps/next/app/page.tsx
"use client";

import { usePostHog } from "posthog-js/react";

export default function Home() {
  const posthog = usePostHog();

  return (
    <main style={{ padding: "2rem", fontFamily: "system-ui" }}>
      <h1>Next.js + PostHog test fixture</h1>
      <p>This page exists to give the bundler something to ship.</p>
      <button onClick={() => posthog?.capture("button_clicked")}>
        Capture event
      </button>
    </main>
  );
}

// apps/error-tracking-upload-source-maps/nuxt-3-6/app.vue
<script setup lang="ts">
const { $posthog } = useNuxtApp();

function captureEvent() {
  $posthog?.capture("button_clicked");
}
</script>

<template>
  <main style="padding: 2rem; font-family: system-ui">
    <h1>Nuxt 3.6 + PostHog test fixture</h1>
    <p>This page exists to give the bundler something to ship.</p>
    <button @click="captureEvent">Capture event</button>
  </main>
</template>
