// apps/basic-integration/react-router/react-router-v7-project/app/components/navbar.tsx
import { NavLink, Link } from "react-router";
import { useAuth } from "~/context/AuthContext";
import { getAvatarUrl } from "~/lib/utils/auth";
import { usePostHog } from '@posthog/react';

export default function Navbar() {
  const { user, isAuthenticated, logout } = useAuth();
  const posthog = usePostHog();

  const handleLogout = () => {
    posthog.capture('user_logged_out');
    posthog.reset();
    logout();
  };

  return (
    <header className="w-full px-8 text-gray-700 bg-white shadow-sm sticky top-0 z-50">
      <div className="container flex flex-col md:flex-row items-center justify-between py-5 mx-auto max-w-7xl">
        <div className="flex flex-col md:flex-row items-center">
          <NavLink to="/" className="flex items-center mb-5 md:mb-0">
            <span className="text-xl font-black text-gray-900 select-none">
              🌍 Country<span className="text-indigo-600">Explorer</span>
            </span>
          </NavLink>
          <nav className="flex flex-wrap items-center ml-0 md:ml-8 md:border-l md:pl-8">
            <NavLink
              to="/"
              end
              className="mr-5 font-medium text-gray-600 hover:text-gray-900"
            >
              Home
            </NavLink>
            <NavLink
              to="/countries"
              className="mr-5 font-medium text-gray-600 hover:text-gray-900"
            >
              Countries
            </NavLink>
            {isAuthenticated && (
              <>
                <NavLink
                  to="/profile"
                  className="mr-5 font-medium text-gray-600 hover:text-gray-900"
                >
                  Profile
                </NavLink>
                <NavLink
                  to="/stats"
                  className="mr-5 font-medium text-gray-600 hover:text-gray-900"
                >
                  Stats
                </NavLink>
              </>
            )}
            <NavLink
              to="/about"
              className="mr-5 font-medium text-gray-600 hover:text-gray-900"
            >
              About
            </NavLink>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          {isAuthenticated && user ? (
            <div className="flex items-center gap-2">
              <Link
                to="/profile"
                className="flex items-center gap-2 px-4 py-2 bg-indigo-50 rounded-lg hover:bg-indigo-100 transition"
              >
                <img
                  src={getAvatarUrl(user.username)}
                  alt={user.username}
                  className="w-8 h-8 rounded-full"
                />
                <span className="font-medium text-gray-700">{user.username}</span>
                <span className="text-yellow-500">⭐ {user.totalPoints}</span>
              </Link>
              <button
                onClick={handleLogout}
                className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium transition"
              >
                Logout
              </button>
            </div>
          ) : (
            <div className="flex gap-3">
              <Link
                to="/login"
                className="px-4 py-2 text-gray-600 hover:text-gray-900 font-medium"
              >
                Login
              </Link>
              <Link
                to="/signup"
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium transition"
              >
                Sign Up
              </Link>
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// apps/basic-integration/nuxt/movies-nuxt-4/components/NavBar.vue
<script setup lang="ts">
const { user, logout } = useAuth()
const posthog = usePostHog()

async function handleLogout() {
  posthog?.capture('user_logged_out', { username: user.value })
  posthog?.reset()
  await logout()
}
</script>

<template>
  <nav
    flex="~ row lg:col"
    justify-evenly items-center
    py5 lg:px5
    border="t lg:r base"
    bg-black
    aria-label="Main navigation"
  >
    <NuxtLink
      v-slot="{ isActive }"
      to="/"
      :title="$t('Home')"
      class="text-2xl transition-colors hover:text-primary flex items-center justify-center"
      :aria-label="$t('Home')"
    >
      <span :class="isActive ? 'i-ph-house-fill text-primary' : 'i-ph-house'" aria-hidden="true" />
      <span class="sr-only">{{ $t('Home') }}</span>
    </NuxtLink>
    <NuxtLink
      v-slot="{ isActive }"
      to="/movie"
      :title="$t('Movies')"
      class="text-2xl transition-colors hover:text-primary flex items-center justify-center"
      :aria-label="$t('Movies')"
    >
      <span :class="isActive ? 'i-ph-film-strip-fill text-primary' : 'i-ph-film-strip'" aria-hidden="true" />
      <span class="sr-only">{{ $t('Movies') }}</span>
    </NuxtLink>
    <NuxtLink
      v-slot="{ isActive }"
      to="/tv"
      :title="$t('TV Shows')"
      class="text-2xl transition-colors hover:text-primary flex items-center justify-center"
      :aria-label="$t('TV Shows')"
    >
      <span :class="isActive ? 'i-ph-television-simple-fill text-primary' : 'i-ph-television-simple'" aria-hidden="true" />
      <span class="sr-only">{{ $t('TV Shows') }}</span>
    </NuxtLink>
    <NuxtLink
      v-slot="{ isActive }"
      to="/search"
      :title="$t('Search')"
      class="text-2xl transition-colors hover:text-primary flex items-center justify-center"
      :aria-label="$t('Search')"
    >
      <span :class="isActive ? 'i-ph-magnifying-glass-fill text-primary' : 'i-ph-magnifying-glass'" aria-hidden="true" />
      <span class="sr-only">{{ $t('Search') }}</span>
    </NuxtLink>
    <div v-if="user" class="flex items-center gap-3">
      <span class="text-sm text-gray-400">{{ user }}</span>
      <button
        type="button"
        class="text-2xl hover:text-primary cursor-pointer transition-colors flex items-center justify-center"
        :title="$t('Logout')"
        :aria-label="$t('Logout')"
        @click="handleLogout"
      >
        <span class="i-ph-sign-out" aria-hidden="true" />
        <span class="sr-only">{{ $t('Logout') }}</span>
      </button>
    </div>
  </nav>
</template>
